// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeVWLcj6VJ_RKHnZRiUJ6mENzU1omMBMI',
    appId: '1:249059573419:web:8b9b836101bb98359f41ee',
    messagingSenderId: '249059573419',
    projectId: 'interactive-calendar-9e700',
    authDomain: 'interactive-calendar-9e700.firebaseapp.com',
    storageBucket: 'interactive-calendar-9e700.firebasestorage.app',
    measurementId: 'G-VPS6HV0DTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHcAj1jxj1R3gT_zT2rrOkIbXFIbGLbjA',
    appId: '1:249059573419:android:b42680ed684f3de09f41ee',
    messagingSenderId: '249059573419',
    projectId: 'interactive-calendar-9e700',
    storageBucket: 'interactive-calendar-9e700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLo2m23-UyQOO5MyfsOVIYgTJLolCBVxg',
    appId: '1:249059573419:ios:430f93657e5ce5a49f41ee',
    messagingSenderId: '249059573419',
    projectId: 'interactive-calendar-9e700',
    storageBucket: 'interactive-calendar-9e700.firebasestorage.app',
    iosBundleId: 'com.example.interactiveCalendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLo2m23-UyQOO5MyfsOVIYgTJLolCBVxg',
    appId: '1:249059573419:ios:430f93657e5ce5a49f41ee',
    messagingSenderId: '249059573419',
    projectId: 'interactive-calendar-9e700',
    storageBucket: 'interactive-calendar-9e700.firebasestorage.app',
    iosBundleId: 'com.example.interactiveCalendarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeVWLcj6VJ_RKHnZRiUJ6mENzU1omMBMI',
    appId: '1:249059573419:web:29a7920f7a2b46729f41ee',
    messagingSenderId: '249059573419',
    projectId: 'interactive-calendar-9e700',
    authDomain: 'interactive-calendar-9e700.firebaseapp.com',
    storageBucket: 'interactive-calendar-9e700.firebasestorage.app',
    measurementId: 'G-7SYEC8KWJY',
  );
}
